### ISSUE TITLE
Help:  AttributeError: 'SoulSeekClient' object has no attribute 'search'. 

### ISSUE THREAD

**Issue by Srm-Akla** [JurgenR/aioslsk#196]
Hi, 

Im trying to understand the api. Although I am aware that this is a noop question. I do not understand why 'SoulSeekClient' has no attribute 'search'.  I have used code from the tutorial. Help is appriciated :)

**CODE:**
```
import asyncio
from aioslsk.client import SoulSeekClient
from aioslsk.settings import Settings, CredentialsSettings
from aioslsk.events import SearchRequest, SearchResult
from aioslsk.events import SearchResultEvent

# Create default settings and configure credentials
settings: Settings = Settings(
    credentials=CredentialsSettings(
        username='USERNAME',
        password='PASSWORD'
    )
)

async def search_result_listener(event: SearchResultEvent):
    print(f"got a search result for query: {event}")


async def main():
    client: SoulSeekClient = SoulSeekClient(settings)

    await client.start()
    await client.login()

    search_request: SearchRequest = await client.search('my query')
    print(f"results: {search_request.results}")

    await client.stop()
asyncio.run(main())
```

**ERROR**:
```
Traceback (most recent call last):
  File "/home/zippidybop/Projects/Spotify_Soulseek/aioslsk-test.py", line 31, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/zippidybop/Projects/Spotify_Soulseek/aioslsk-test.py", line 25, in main
    search_request: SearchRequest = await client.search('my query')
AttributeError: 'SoulSeekClient' object has no attribute 'search'. Did you mean: 'searches'?
```

**Comment by Srm-Akla** [comment]
Awesome, Thanks!
