### ISSUE TITLE
Unable to change my server port

### ISSUE THREAD

**Issue by Srm-Akla** [JurgenR/aioslsk#199]
Hi, 

I wanted to change my server port. However I am getting this error. I am assuming this is because of default server port 2416. 

**CODE**
```
import asyncio
from aioslsk.client import SoulSeekClient
from aioslsk.settings import ServerSettings, Settings, CredentialsSettings
from aioslsk.events import SearchRequest, SearchResult
from aioslsk.events import SearchResultEvent

# Create default settings and configure credentials
settings: Settings = Settings(
    credentials=CredentialsSettings(
        username='USERNAME',
        password='PASSWORD'
    ),
    server = ServerSettings(
        port=2234,
    )
)

async def search_result_listener(event: SearchResultEvent):
    print(f"got a search result for query: {event}")

async def main():
    client: SoulSeekClient = SoulSeekClient(settings)

    await client.start()
    await client.login()
    search_request: SearchRequest = await client.searches.search('nina simone')
    print(f"results: {search_request.results}")
    await client.stop()

asyncio.run(main())
```

**ERROR**
```
Traceback (most recent call last):
  File "/home/zippidybop/Projects/Spotify_Soulseek/aioslsk-test.py", line 8, in <module>
    settings: Settings = Settings(
  File "/home/zippidybop/Projects/Spotify_Soulseek/.venv/lib/python3.10/site-packages/pydantic_settings/main.py", line 84, in __init__
    super().__init__(
  File "/home/zippidybop/Projects/Spotify_Soulseek/.venv/lib/python3.10/site-packages/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Settings
server
  Extra inputs are not permitted [type=extra_forbidden, input_value=ServerSettings(hostname='...auto=False, timeout=10)), input_type=ServerSettings]
    For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden
```

Thanks! :smiley:

**Comment by JurgenR** [comment]
@Srm-Akla the server settings are part of the Network settings, so either you will need to create an object of that first or just change the port attribute after creating the `Settings` object.

So something like:

```python
Settings(
    network=NetworkSettings(
        server=ServerSettings(
             port=2234
        )
    )
)
```

Or simply:

```python
settings.network.server.port = 2234
```

Small question, is it the server port or listening port you're trying to change?

**Comment by Srm-Akla** [comment]
I was getting the following output when trying to search. Therefore I decided to try and connect to port 2234, which is the same port as nicotine+

```
attempted to report shares without valid session
results: []
server.slsknet.org:2416 : read error
```

**Comment by JurgenR** [comment]
Nicotine+ listens by default on port 2234 (other peers connect to this port for sending results, sharing files, etc), the server port is always the same (2416) and probably is not what you wanted to change.

I've changed your code a bit to wait after sending the search request. The `client.searches.search` simply sends out the request to the server, it does not wait for any results thus this sleep is needed to allow other peers to connect to you and send their response. I've also added logging to a file since some messages were being logged to the console, this should be cleaner and allows you to see what's going on in the background. The file should be created in your current working directory and is named `aioslsk.log`, it should be overwritten each time the script is run.

I would also like to remind you of the first warning in the USAGE guide, connecting too many times to the server could result in a ban so it's best to leave some time between attempts. I hope this has not already happened to you.

```python
import asyncio
from aioslsk.client import SoulSeekClient
from aioslsk.settings import Settings, CredentialsSettings, NetworkSettings, ListeningSettings
from aioslsk.search.model import SearchRequest, SearchResult
from aioslsk.events import SearchResultEvent
import logging

# Log stuff to aioslsk.log in the current directory
logging.basicConfig(
    filename='aioslsk.log',
    filemode='w',
    format='%(asctime)s.%(msecs)d %(name)s %(levelname)s %(message)s',
    datefmt='%H:%M:%S',
    level=logging.DEBUG
)


# Create default settings and configure credentials
settings: Settings = Settings(
    credentials=CredentialsSettings(
        username='USERNAME',
        password='PASSWORD'
    ),
    network=NetworkSettings(
        listening=ListeningSettings(
             port=2234,
             obfuscated_port=0
        )
    )
)

async def search_result_listener(event: SearchResultEvent):
    print(f"got a search result for query: {event.query.query} : {event.result}")


async def main():
    client: SoulSeekClient = SoulSeekClient(settings)

    await client.start()
    await client.login()
    
    # Sends out the search request, but does not actually wait for the results
    search_request: SearchRequest = await client.searches.search('nina simone')

    # Wait for 30s until some search responses arrive
    await asyncio.sleep(30)
    
    print(f"results: {search_request.results}")

    await client.stop()

asyncio.run(main())
```

**Comment by Srm-Akla** [comment]
Thank you very much! You are right! It is easier to read through the log than print the output.
